### PR TITLE
Date Filtering for ORM

### PR DESCRIPTION
**Pull request by ghost**
# Please Merge

- whereMonth and whereDay for ORM

Part of issue #28

### CODE REVIEW

**Comment by LuckyCyborg** [comment]
@Kingorgg Would be very nice to note somehow that the **Database Backup** is an **extension** living on the **Shared** namespace, given as "some cool stuff", but not a supported NATIVE API.

In other hand, the Database Backup does not exists on the bare application form `nova-framework/app`, which is supposed to be the starting point for developers.

**Comment by ghost** [comment]
@LuckyCyborg Changes made.

**Comment by LuckyCyborg** [comment]
Thanks, Daniel!

**Comment by dcblogdev** [comment]
thanks 👍

**Pull request merged**
